version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: compareflow-postgres
    environment:
      POSTGRES_USER: compareflow
      POSTGRES_PASSWORD: compareflow123
      POSTGRES_DB: compareflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compareflow"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: